// Initiate variables
var randomNumber;
var maxValue = 1000;
var minValue = -1000;
var inputValue;
var inputValueToInt;
var hasGuessed = false;
var numOfGuesses = 0;

// Intro message, initiate random number, and call run function
alert("Welcome to my random number guesser!\nThe goal of this game is to guess a random number generated by the computer between " + minValue + " and " + maxValue + ".\nGood luck and have fun!");
randomNumber = Math.floor(Math.random() * maxValue) + minValue;
run();

// run function
function run() {
  !hasGuessed ? inputValue = prompt("What number do you guess?") : inputValue = prompt("Oops, wrong number! Want to take another guess?");
  inputValueToInt = parseInt(inputValue);
  numOfGuesses++;
  if (inputValue == randomNumber) {
    alert("Congrats, you guessed the correct number!\nYou guessed the number " + randomNumber + " in " + numOfGuesses + " guesses.");
  } else {
    hasGuessed = true;
    run();
  }
}