// Initiate variables
var randomNumber;
var maxValue = 10;
var minValue = 1;
var inputValue;
var inputValueToInt;
var hasGuessed = false;

//Intro message, initiate random number
alert("Welcome to my random number guesser!\nThe goal of this game is to guess a random number generated by the computer between " + minValue + " and " + maxValue + ".\nGood luck and have fun!");
randomNumber = Math.floor(Math.random() * maxValue) + minValue;

inputValue = prompt("What number do you guess?"); // Ask which number to input
inputValueToInt = parseInt(inputValue); // Turn string to int
inputValue == randomNumber ? alert("Congrats, you guessed the correct number!\nThe number was " + randomNumber + "\nYou guessed the number " + inputValueToInt) : alert("You lost, you did not guess the correct number.\nThe number was " + randomNumber + "\nYou guessed the number " + inputValueToInt); // Check if the generated number is equal to the inputted number. If so, tell the player they won and if not, tell the player they lost.